// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcfhaqbypdhbcdiztgip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZmhhcWJ5cGRoYmNkaXp0Z2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNjg0MDQsImV4cCI6MjA3OTc0NDQwNH0.4W8p2AnrAN-Gfv2RsuBR5TPgNDNpM9SXSi4k5S0a-mY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});