// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crfpmdqzepjteyelvyyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZnBtZHF6ZXBqdGV5ZWx2eXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNjUxNDgsImV4cCI6MjA4OTg0MTE0OH0.zJo1upWdAx2P8HHBn6NdLimHF7fnC8EAuJc1q1STd_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});